version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.17.6
    ports:
      - 9200
      - 9300
    environment:
      - "discovery.type=single-node"
      - "cluster.name=personium"
      - "network.host=0.0.0.0"
      - "action.auto_create_index=.watches,.triggered_watches,.watcher-history-*"
      - "action.destructive_requires_name=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://localhost"
      - "indices.fielddata.cache.size=80%"
      - "xpack.security.enabled=false"

  activemq:
    image: symptoma/activemq:5.16.3
    ports:
      - 61616
      - 8161

  memcached-lock:
    image: memcached:1.6.7
    ports:
      - 11211

  memcached-cache:
    image: memcached:1.6.7
    ports:
      - 11211

  personium-engine:
    build:
      context: ./dockerfiles/personium-engine
      args:
        - ENGINE_VER=1.6.0
        - http_proxy=${HTTP_PROXY:-}
        - https_proxy=${HTTPS_PROXY:-}
    image: personium-engine:1.6.0
    environment: 
      JAVA_OPTS: "-Dio.personium.configurationFile=/personium/personium-engine/personium-unit-config.properties"
    ports:
      - 8080
    volumes:
      - personium_data:/personium_nfs

  personium-core-dev:
    image: java17-dev
    build:
      context: ./dockerfiles/java17-dev
      args:
        - http_proxy=${HTTP_PROXY:-}
        - https_proxy=${HTTPS_PROXY:-}
    user: devuser
    environment:
      - http_proxy=${HTTP_PROXY:-}
      - https_proxy=${HTTPS_PROXY:-}
      - no_proxy=${NO_PROXY:-}
    volumes:
      - personium_data:/personium_nfs


  # nginx:
  #   build:
  #     context: ./dockerfiles/nginx
  #   ports:
  #     - 80:80

networks:
  default:

volumes:
  personium_data:
    driver: local